name:        hemmet
version:     0.1.0.0
category:    Text
description: Expander for Emmet/ZenCoding-like snippets
github:      astynax/hemmet

author:      Aleksey Pirogov
license:     BSD3
maintainer:  astynax84@gmail.com
copyright:   Aleksey Pirogov aka astynax

extra-source-files:
  - README.md

default-extensions:
  - GADTs
  - LambdaCase
  - MultiParamTypeClasses
  - OverloadedStrings
  - RecordWildCards
  - TupleSections
  - ViewPatterns

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Wmissing-exported-signatures

_executable-options: &exe-opts
  ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

_typical-executable: &exe
  <<: *exe-opts
  main: Main.hs
  dependencies:
    - base
    - hemmet

executables:
  hemmet:
    <<: *exe
    source-dirs:
      - app/hemmet
  hemmeti:
    <<: *exe
    source-dirs:
      - app/hemmeti

library:
  source-dirs:
    - src
  dependencies:
    - base
    - brick
    - mtl
    - megaparsec
    - optparse-applicative
    - text
    - vty

tests:
  main:
    <<: *exe-opts
    source-dirs:
      - test
    main: Spec.hs
    dependencies:
      - base
      - bytestring
      - filepath
      - Glob
      - hemmet
      - hspec
      - megaparsec
      - tasty
      - tasty-golden
      - tasty-hspec
      - text

