name:        hemmet
version:     0.1.0.0
category:    Text
description: Expander for Emmet/ZenCoding-like snippets
github:      astynax/hemmet

author:      Aleksey Pirogov
license:     BSD3
maintainer:  astynax84@gmail.com
copyright:   Aleksey Pirogov aka astynax

extra-source-files:
  - README.md

default-extensions:
  - GADTs
  - LambdaCase
  - MultiParamTypeClasses
  - OverloadedStrings
  - RecordWildCards
  - TupleSections

_typical_executable: &exe
  main: Main.hs
  ghc-options:
    - -Werror
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  dependencies:
    - base
    - hemmet

executables:
  hemmet:
    <<: *exe
    source-dirs:
      - app/hemmet
  hemmeti:
    <<: *exe
    source-dirs:
      - app/hemmeti

library:
  source-dirs:
    - src
  dependencies:
    - base
    - brick
    - data-default
    - mtl
    - megaparsec
    - optparse-applicative
    - text
    - vty
  ghc-options:
    - -Wall

tests:
  main:
    source-dirs:
      - test
    main: Spec.hs
    dependencies:
      - base
      - bytestring
      - filepath
      - Glob
      - hemmet
      - hspec
      - mtl
      - megaparsec
      - tasty
      - tasty-golden
      - tasty-hspec
      - text
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
